export const VK_URL = 'https://vk.com/crypto.ouroboros'
export const FACEBOOK_URL = 'https://www.facebook.com/ouroboros.crypto/'
export const YOUTUBE_URL = 'https://www.youtube.com/channel/UCqZ9KHRhQIXBWdBiNywSuDA?view_as=subscriber'
export const INSTAGRAM_URL = 'https://www.instagram.com/ouroboros.crypto/'
export const TELEGRAM_URL = 'https://t.me/ouroboros_BT'
export const EMAIL_URL = 'admin@ouroboros-crypto.com'
